# Generated by Django 4.2.1 on 2023-05-18 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='audiofile',
            field=models.FileField(upload_to=''),
        ),
    ]
